/**
 * Regenerates vendored stop-word lists from `stopwords-iso` (research R5).
 *
 * Run: node scripts/update-stopwords.ts
 */
import { createRequire } from 'node:module'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const require = createRequire(import.meta.url)
const iso = require('stopwords-iso') as Record<string, string[]>
const isoVersion = (require('stopwords-iso/package.json') as { version: string }).version

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

function generate(lang: 'id' | 'en', sourceKey: string): void {
  const raw = iso[sourceKey]
  if (!Array.isArray(raw)) throw new Error(`stopwords-iso has no list for "${sourceKey}"`)
  const words = [...new Set(raw.map((w) => String(w).toLowerCase().trim()).filter(Boolean))].sort()
  const body = words.map((w) => `  ${JSON.stringify(w)},`).join('\n')
  const content = `// AUTO-GENERATED by scripts/update-stopwords.ts — DO NOT EDIT BY HAND.
// Source: stopwords-iso@${isoVersion} (MIT), key "${sourceKey}", ${words.length} entries.
export const STOP_WORDS: readonly string[] = [
${body}
]
`
  writeFileSync(join(root, 'src', 'core', 'stopwords', `${lang}.ts`), content, 'utf8')
  console.log(`${lang}: ${words.length} stop words`)
}

generate('id', 'id')
generate('en', 'en')
